/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { etsy_listing_ctx$_T } from './etsy_listing_ctx$_b.js'
import type { loading_s3_etsy_listing_a$_T } from './loading_s3_etsy_listing_a$_b.js'
import type { loading_s3_etsy_listing_image_a$_T } from './loading_s3_etsy_listing_image_a$_b.js'
import type { s3_etsy_listing_a$_T } from './s3_etsy_listing_a$_b.js'
import type { s3_etsy_listing_image_a$_T } from './s3_etsy_listing_image_a$_b.js'
export interface etsy_cache_ctx_I {
	etsy_listing_ctx$?:etsy_listing_ctx$_T
	loading_s3_etsy_listing_a$?:loading_s3_etsy_listing_a$_T
	loading_s3_etsy_listing_image_a$?:loading_s3_etsy_listing_image_a$_T
	s3_etsy_listing_a$?:s3_etsy_listing_a$_T
	s3_etsy_listing_image_a$?:s3_etsy_listing_image_a$_T
}